name: campus_subsystem
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.3.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_speed_dial: ^6.0.0
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.4
  intl: ^0.17.0
  firebase_storage: ^11.0.6
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  http: ^0.13.4
  file_picker: ^5.2.2
  loading_animation_widget: ^1.2.0+2
  internet_connection_checker: ^0.0.1+4
  flutter_hooks: ^0.18.5+1
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  easy_pdf_viewer: ^1.0.6
  flutterfire: ^0.0.1
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.1.2
  cached_network_image: ^3.2.1
  emoji_picker_flutter: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
     - family: Custom
       fonts:
         - asset: assets/fonts/BubblegumSans.ttf

     - family: Sticky
       fonts:
         - asset: assets/fonts/StickNoBills-VariableFont_wght.ttf

     - family: Bold
       fonts:
         - asset: assets/fonts/BebasNeue-Regular.ttf

     - family: Narrow
       fonts:
         - asset: assets/fonts/PTSansNarrow-Bold.ttf

     - family: Muli
       fonts:
         - asset: assets/fonts/Muli.ttf

     - family: MuliBold
       fonts:
         - asset: assets/fonts/Muli-Bold.ttf
